spring.application.name=activityservice

# ===============================
# Server
# ===============================
server.port=8082

# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/myfitness
spring.data.mongodb.database=myfitness

spring.data.mongodb.auto-index-creation=true

