spring.application.name=activity-service

# ===============================
# Server
# ===============================
server.port=8081

# ==================================
#RabbitMQ Configuration
# ================================
spring.rabbitmq.host = localhost
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest


# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/myfitness
spring.data.mongodb.database=myfitness

spring.data.mongodb.auto-index-creation=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

rabbitmq.exchange.name = fitness.exchange
rabbitmq.queue.name = activity.queue
rabbitmq.routing.key = activity.tracking

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
