spring.application.name=ai-service

server.port=8082

# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/fitnessrecommendation
spring.data.mongodb.database=fitnessrecommendation

# Eureka Service
# =================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# ==================================
#RabbitMQ Configuration
# ================================
spring.rabbitmq.host = localhost
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest

rabbitmq.exchange.name = fitness.exchange
rabbitmq.queue.name = activity.queue
rabbitmq.routing.key = activity.tracking

# Gemini API
gemini.api.url = ${GEMINI_API_URL}
gemini.api.key = ${GEMINI_API_KEY}


